######################################################################
#
# File name : uart_tb_elaborate.do
# Created on: Sun Nov 24 21:55:59 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt +acc=npr -L xilinx_vip -L xpm -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.uart_tb xil_defaultlib.glbl -o uart_tb_opt

quit -force
