######################################################################
#
# File name : uav_sar_wrapper_compile.do
# Created on: Sun Sep 24 21:44:12 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" "+incdir+C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/sim/uav_sar_zynq_ultra_ps_e_0_0_vip_wrapper.v" \

vcom  -93 -work xil_defaultlib  \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/sim/uav_sar_proc_sys_reset_0_0.vhd" \

vlog  -incr -work xil_defaultlib  "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" "+incdir+C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_xbar_0/sim/uav_sar_xbar_0.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/5342/src/ad9269_sample .v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/5342/src/clk_div.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_ad9269_sample_ctrl_0_0/sim/uav_sar_ad9269_sample_ctrl_0_0.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/sim/uav_sar_axi_data_fifo_0_0.v" \

vcom  -93 -work xil_defaultlib  \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_0/sim/uav_sar_axi_dma_0_0.vhd" \

vlog  -incr -work xil_defaultlib  "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" "+incdir+C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axis_data_fifo_0_0/sim/uav_sar_axis_data_fifo_0_0.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0_clk_wiz.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0.v" \

vcom  -93 -work xil_defaultlib  \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/util_ds_buf.vhd" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/sim/uav_sar_util_ds_buf_0_0.vhd" \

vlog  -incr -work xil_defaultlib  "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" "+incdir+../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" "+incdir+C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_pc_0/sim/uav_sar_auto_pc_0.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_0/sim/uav_sar_auto_us_0.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/sim/uav_sar.v" \
"../../../../uav_sar.srcs/sources_1/bd/uav_sar/hdl/uav_sar_wrapper.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

