######################################################################
#
# File name : uart_tb_simulate.do
# Created on: Mon Nov 25 20:07:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xilinx_vip -L xpm -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.uart_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {uart_tb_wave.do}

view wave
view structure
view signals

do {uart_tb.udo}

run 1000ns
