######################################################################
#
# File name : uart_rx_tb.udo
# Created on: Mon Nov 25 16:49:50 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
