######################################################################
#
# File name : uart_tb.udo
# Created on: Sun Nov 24 21:58:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
