######################################################################
#
# File name : uart_tb_wave.do
# Created on: Sun Nov 24 21:58:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
