######################################################################
#
# File name : utc_time_tb.udo
# Created on: Tue Nov 26 15:29:22 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
