######################################################################
#
# File name : utc_time_tb_wave.do
# Created on: Tue Nov 26 15:29:22 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
