#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : uav_sar.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Dec 30 11:09:34 +0800 2025
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: uav_sar.sh [-help]
# usage: uav_sar.sh [-lib_map_path]
# usage: uav_sar.sh [-noclean_files]
# usage: uav_sar.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'uav_sar.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_7 zynq_ultra_ps_e_vip_v1_0_7 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_21 fifo_generator_v13_2_5 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 lib_pkg_v1_0_2 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_23 axi_sg_v4_1_13 axi_dma_v7_1_22 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_3 axi_protocol_converter_v2_1_21 axi_clock_converter_v2_1_20 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "uav_sar.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/Xilinx_vitis2020/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/sim/uav_sar_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/sim/uav_sar_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_xbar_0/sim/uav_sar_xbar_0.v" \
    $ref_dir/../../../bd/uav_sar/ipshared/2577/src/ad9269_sample\\ .v \
    "$ref_dir/../../../bd/uav_sar/ipshared/2577/src/clk_div.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_ad9269_sample_ctrl_0_0/sim/uav_sar_ad9269_sample_ctrl_0_0.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/sim/uav_sar_axi_data_fifo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_23 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/af86/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_22 $vhdlan_opts \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/0fb1/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_axi_dma_0_0/sim/uav_sar_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/sim/uav_sar_util_ds_buf_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_xbar_1/sim/uav_sar_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/50d0/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_axis_data_fifo_0_1/sim/uav_sar_axis_data_fifo_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_axi_dma_0_1/sim/uav_sar_axi_dma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_axi_data_fifo_0_1/sim/uav_sar_axi_data_fifo_0_1.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/src/fifo_generator_0/sim/fifo_generator_0.v" \
    "$ref_dir/../../../bd/uav_sar/ipshared/f421/hdl/uart_rx.v" \
    "$ref_dir/../../../bd/uav_sar/ipshared/f421/hdl/uart_uav_data_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/uav_sar/ipshared/f421/hdl/utc_time.v" \
    "$ref_dir/../../../bd/uav_sar/ipshared/f421/hdl/uart_uav_data_v1_0.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/sim/uav_sar_uart_uav_data_0_4.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/sim/bd_9e4d.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/sim/bd_9e4d_ila_lib_0.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_system_ila_1_0/sim/uav_sar_system_ila_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8dfa/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_auto_pc_0/sim/uav_sar_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/7589/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/07be/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8b3d" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../uav_sar.srcs/sources_1/bd/uav_sar/ipshared/c968/hdl/verilog" +incdir+"E:/Xilinx_vitis2020/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_auto_us_0/sim/uav_sar_auto_us_0.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_auto_ds_0/sim/uav_sar_auto_ds_0.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_auto_ds_1/sim/uav_sar_auto_ds_1.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_auto_ds_2/sim/uav_sar_auto_ds_2.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_auto_us_1/sim/uav_sar_auto_us_1.v" \
    "$ref_dir/../../../bd/uav_sar/ip/uav_sar_auto_us_2/sim/uav_sar_auto_us_2.v" \
    "$ref_dir/../../../bd/uav_sar/sim/uav_sar.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.uav_sar xil_defaultlib.glbl -o uav_sar_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./uav_sar_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./uav_sar.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key uav_sar_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc uav_sar_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./uav_sar.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: uav_sar.sh [-help]\n\
Usage: uav_sar.sh [-lib_map_path]\n\
Usage: uav_sar.sh [-reset_run]\n\
Usage: uav_sar.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
