# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/uav_sar.bd
# Block Designs: The module: 'uav_sar' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/uav_sar_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==uav_sar_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_interconnect_0_0/uav_sar_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_interconnect_0_0 || ORIG_REF_NAME==uav_sar_axi_interconnect_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/uav_sar_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_proc_sys_reset_0_0 || ORIG_REF_NAME==uav_sar_proc_sys_reset_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_xbar_0/uav_sar_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_xbar_0 || ORIG_REF_NAME==uav_sar_xbar_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_interconnect_0_1/uav_sar_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_interconnect_0_1 || ORIG_REF_NAME==uav_sar_axi_interconnect_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_ad9269_sample_ctrl_0_0/uav_sar_ad9269_sample_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_ad9269_sample_ctrl_0_0 || ORIG_REF_NAME==uav_sar_ad9269_sample_ctrl_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/uav_sar_axi_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_0 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_0/uav_sar_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_0 || ORIG_REF_NAME==uav_sar_axi_dma_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_clk_wiz_0_0 || ORIG_REF_NAME==uav_sar_clk_wiz_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/uav_sar_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_util_ds_buf_0_0 || ORIG_REF_NAME==uav_sar_util_ds_buf_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_xbar_1/uav_sar_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_xbar_1 || ORIG_REF_NAME==uav_sar_xbar_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axis_data_fifo_0_1/uav_sar_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axis_data_fifo_0_1 || ORIG_REF_NAME==uav_sar_axis_data_fifo_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_1 || ORIG_REF_NAME==uav_sar_axi_dma_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_1/uav_sar_axi_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_1 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/uav_sar_uart_uav_data_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_uart_uav_data_0_4 || ORIG_REF_NAME==uav_sar_uart_uav_data_0_4} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/src/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/uav_sar_system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_system_ila_1_0 || ORIG_REF_NAME==uav_sar_system_ila_1_0} -quiet] -quiet

# Block Designs: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/bd_9e4d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9e4d || ORIG_REF_NAME==bd_9e4d} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/bd_9e4d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9e4d_ila_lib_0 || ORIG_REF_NAME==bd_9e4d_ila_lib_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_pc_0/uav_sar_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_pc_0 || ORIG_REF_NAME==uav_sar_auto_pc_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_0/uav_sar_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_0 || ORIG_REF_NAME==uav_sar_auto_us_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_0/uav_sar_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_0 || ORIG_REF_NAME==uav_sar_auto_ds_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_1/uav_sar_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_1 || ORIG_REF_NAME==uav_sar_auto_ds_1} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_2/uav_sar_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_2 || ORIG_REF_NAME==uav_sar_auto_ds_2} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_1/uav_sar_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_1 || ORIG_REF_NAME==uav_sar_auto_us_1} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_2/uav_sar_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_2 || ORIG_REF_NAME==uav_sar_auto_us_2} -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/uav_sar_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/uav_sar_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==uav_sar_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/uav_sar_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_proc_sys_reset_0_0 || ORIG_REF_NAME==uav_sar_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/uav_sar_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_proc_sys_reset_0_0 || ORIG_REF_NAME==uav_sar_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/uav_sar_axi_data_fifo_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_0 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/uav_sar_axi_data_fifo_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_0/uav_sar_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_0 || ORIG_REF_NAME==uav_sar_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_0/uav_sar_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_0 || ORIG_REF_NAME==uav_sar_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_clk_wiz_0_0 || ORIG_REF_NAME==uav_sar_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_clk_wiz_0_0 || ORIG_REF_NAME==uav_sar_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/uav_sar_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_util_ds_buf_0_0 || ORIG_REF_NAME==uav_sar_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/uav_sar_util_ds_buf_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_xbar_1/uav_sar_xbar_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axis_data_fifo_0_1/uav_sar_axis_data_fifo_0_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_1 || ORIG_REF_NAME==uav_sar_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_1 || ORIG_REF_NAME==uav_sar_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_1/uav_sar_axi_data_fifo_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_1 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_1/uav_sar_axi_data_fifo_0_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/src/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/src/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9e4d_ila_lib_0 || ORIG_REF_NAME==bd_9e4d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9e4d_ila_lib_0 || ORIG_REF_NAME==bd_9e4d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/bd_9e4d_ila_lib_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/bd_9e4d_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/uav_sar_system_ila_1_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_pc_0/uav_sar_auto_pc_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_0/uav_sar_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_0 || ORIG_REF_NAME==uav_sar_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_0/uav_sar_auto_us_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_0/uav_sar_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_0 || ORIG_REF_NAME==uav_sar_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_0/uav_sar_auto_ds_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_1/uav_sar_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_1 || ORIG_REF_NAME==uav_sar_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_1/uav_sar_auto_ds_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_2/uav_sar_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_2 || ORIG_REF_NAME==uav_sar_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_2/uav_sar_auto_ds_2_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_1/uav_sar_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_1 || ORIG_REF_NAME==uav_sar_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_1/uav_sar_auto_us_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_2/uav_sar_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_2 || ORIG_REF_NAME==uav_sar_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_2/uav_sar_auto_us_2_ooc.xdc

# XDC: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/uav_sar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uav_sar'. Do not add the DONT_TOUCH constraint.

# Block Designs: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/uav_sar.bd
# Block Designs: The module: 'uav_sar' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/uav_sar_zynq_ultra_ps_e_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==uav_sar_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_interconnect_0_0/uav_sar_axi_interconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_interconnect_0_0 || ORIG_REF_NAME==uav_sar_axi_interconnect_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/uav_sar_proc_sys_reset_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_proc_sys_reset_0_0 || ORIG_REF_NAME==uav_sar_proc_sys_reset_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_xbar_0/uav_sar_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_xbar_0 || ORIG_REF_NAME==uav_sar_xbar_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_interconnect_0_1/uav_sar_axi_interconnect_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_interconnect_0_1 || ORIG_REF_NAME==uav_sar_axi_interconnect_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_ad9269_sample_ctrl_0_0/uav_sar_ad9269_sample_ctrl_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_ad9269_sample_ctrl_0_0 || ORIG_REF_NAME==uav_sar_ad9269_sample_ctrl_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/uav_sar_axi_data_fifo_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_0 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_0/uav_sar_axi_dma_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_0 || ORIG_REF_NAME==uav_sar_axi_dma_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_clk_wiz_0_0 || ORIG_REF_NAME==uav_sar_clk_wiz_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/uav_sar_util_ds_buf_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_util_ds_buf_0_0 || ORIG_REF_NAME==uav_sar_util_ds_buf_0_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_xbar_1/uav_sar_xbar_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_xbar_1 || ORIG_REF_NAME==uav_sar_xbar_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axis_data_fifo_0_1/uav_sar_axis_data_fifo_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axis_data_fifo_0_1 || ORIG_REF_NAME==uav_sar_axis_data_fifo_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_1 || ORIG_REF_NAME==uav_sar_axi_dma_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_1/uav_sar_axi_data_fifo_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_1 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_1} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/uav_sar_uart_uav_data_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_uart_uav_data_0_4 || ORIG_REF_NAME==uav_sar_uart_uav_data_0_4} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/src/fifo_generator_0/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/uav_sar_system_ila_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_system_ila_1_0 || ORIG_REF_NAME==uav_sar_system_ila_1_0} -quiet] -quiet

# Block Designs: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/bd_9e4d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9e4d || ORIG_REF_NAME==bd_9e4d} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/bd_9e4d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9e4d_ila_lib_0 || ORIG_REF_NAME==bd_9e4d_ila_lib_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_pc_0/uav_sar_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_pc_0 || ORIG_REF_NAME==uav_sar_auto_pc_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_0/uav_sar_auto_us_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_0 || ORIG_REF_NAME==uav_sar_auto_us_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_0/uav_sar_auto_ds_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_0 || ORIG_REF_NAME==uav_sar_auto_ds_0} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_1/uav_sar_auto_ds_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_1 || ORIG_REF_NAME==uav_sar_auto_ds_1} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_2/uav_sar_auto_ds_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_2 || ORIG_REF_NAME==uav_sar_auto_ds_2} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_1/uav_sar_auto_us_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_1 || ORIG_REF_NAME==uav_sar_auto_us_1} -quiet] -quiet

# IP: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_2/uav_sar_auto_us_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_2 || ORIG_REF_NAME==uav_sar_auto_us_2} -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/uav_sar_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_zynq_ultra_ps_e_0_0/uav_sar_zynq_ultra_ps_e_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==uav_sar_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/uav_sar_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_proc_sys_reset_0_0 || ORIG_REF_NAME==uav_sar_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_proc_sys_reset_0_0/uav_sar_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_proc_sys_reset_0_0 || ORIG_REF_NAME==uav_sar_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/uav_sar_axi_data_fifo_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_0 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_0/uav_sar_axi_data_fifo_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_0/uav_sar_axi_dma_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_0 || ORIG_REF_NAME==uav_sar_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_0/uav_sar_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_0 || ORIG_REF_NAME==uav_sar_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_clk_wiz_0_0 || ORIG_REF_NAME==uav_sar_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_clk_wiz_0_0 || ORIG_REF_NAME==uav_sar_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_clk_wiz_0_0/uav_sar_clk_wiz_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/uav_sar_util_ds_buf_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_util_ds_buf_0_0 || ORIG_REF_NAME==uav_sar_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_util_ds_buf_0_0/uav_sar_util_ds_buf_0_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_xbar_1/uav_sar_xbar_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axis_data_fifo_0_1/uav_sar_axis_data_fifo_0_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_1 || ORIG_REF_NAME==uav_sar_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_dma_0_1 || ORIG_REF_NAME==uav_sar_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_dma_0_1/uav_sar_axi_dma_0_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_1/uav_sar_axi_data_fifo_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_axi_data_fifo_0_1 || ORIG_REF_NAME==uav_sar_axi_data_fifo_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_axi_data_fifo_0_1/uav_sar_axi_data_fifo_0_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/src/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_uart_uav_data_0_4/src/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9e4d_ila_lib_0 || ORIG_REF_NAME==bd_9e4d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9e4d_ila_lib_0 || ORIG_REF_NAME==bd_9e4d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/ip/ip_0/bd_9e4d_ila_lib_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/bd_0/bd_9e4d_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_system_ila_1_0/uav_sar_system_ila_1_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_pc_0/uav_sar_auto_pc_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_0/uav_sar_auto_us_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_0 || ORIG_REF_NAME==uav_sar_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_0/uav_sar_auto_us_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_0/uav_sar_auto_ds_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_0 || ORIG_REF_NAME==uav_sar_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_0/uav_sar_auto_ds_0_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_1/uav_sar_auto_ds_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_1 || ORIG_REF_NAME==uav_sar_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_1/uav_sar_auto_ds_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_2/uav_sar_auto_ds_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_ds_2 || ORIG_REF_NAME==uav_sar_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_ds_2/uav_sar_auto_ds_2_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_1/uav_sar_auto_us_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_1 || ORIG_REF_NAME==uav_sar_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_1/uav_sar_auto_us_1_ooc.xdc

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_2/uav_sar_auto_us_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uav_sar_auto_us_2 || ORIG_REF_NAME==uav_sar_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/ip/uav_sar_auto_us_2/uav_sar_auto_us_2_ooc.xdc

# XDC: E:/vivado_axidma3/uav_sar.srcs/sources_1/bd/uav_sar/uav_sar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uav_sar'. Do not add the DONT_TOUCH constraint.
